apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: helionest
  labels:
    app: backend
    app.kubernetes.io/part-of: helionest-ai
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
