"""initial tables

Revision ID: 555c5630c6bb
Revises: 
Create Date: 2026-03-02 10:59:22.485187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '555c5630c6bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('formatted_address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_lat'), 'locations', ['lat'], unique=False)
    op.create_index(op.f('ix_locations_lon'), 'locations', ['lon'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('property_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('heat_score_north', sa.Float(), nullable=True),
    sa.Column('heat_score_south', sa.Float(), nullable=True),
    sa.Column('heat_score_east', sa.Float(), nullable=True),
    sa.Column('heat_score_west', sa.Float(), nullable=True),
    sa.Column('solar_potential_score', sa.Float(), nullable=True),
    sa.Column('outdoor_comfort_score', sa.Float(), nullable=True),
    sa.Column('annual_heat_risk_score', sa.Float(), nullable=True),
    sa.Column('annual_heat_risk_level', sa.String(length=20), nullable=True),
    sa.Column('worst_car_heat_hour', sa.Integer(), nullable=True),
    sa.Column('worst_car_interior_temp_c', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_analyses_id'), 'property_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_property_analyses_location_id'), 'property_analyses', ['location_id'], unique=False)
    op.create_table('saved_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_properties_id'), 'saved_properties', ['id'], unique=False)
    op.create_index(op.f('ix_saved_properties_location_id'), 'saved_properties', ['location_id'], unique=False)
    op.create_index(op.f('ix_saved_properties_user_id'), 'saved_properties', ['user_id'], unique=False)
    op.create_table('solar_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solar_noon', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('day_length_hours', sa.Float(), nullable=True),
    sa.Column('max_elevation_deg', sa.Float(), nullable=True),
    sa.Column('solar_noon_azimuth_deg', sa.Float(), nullable=True),
    sa.Column('daily_irradiance_kwh', sa.Float(), nullable=True),
    sa.Column('peak_sun_hours', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solar_snapshots_id'), 'solar_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_solar_snapshots_location_id'), 'solar_snapshots', ['location_id'], unique=False)
    op.create_index(op.f('ix_solar_snapshots_snapshot_date'), 'solar_snapshots', ['snapshot_date'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('feels_like_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('conditions', sa.String(length=100), nullable=True),
    sa.Column('heat_index_c', sa.Float(), nullable=True),
    sa.Column('wind_chill_c', sa.Float(), nullable=True),
    sa.Column('comfort_score', sa.Float(), nullable=True),
    sa.Column('comfort_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_fetched_at'), 'weather_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_id'), 'weather_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_location_id'), 'weather_snapshots', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_snapshots_location_id'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_id'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_fetched_at'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_solar_snapshots_snapshot_date'), table_name='solar_snapshots')
    op.drop_index(op.f('ix_solar_snapshots_location_id'), table_name='solar_snapshots')
    op.drop_index(op.f('ix_solar_snapshots_id'), table_name='solar_snapshots')
    op.drop_table('solar_snapshots')
    op.drop_index(op.f('ix_saved_properties_user_id'), table_name='saved_properties')
    op.drop_index(op.f('ix_saved_properties_location_id'), table_name='saved_properties')
    op.drop_index(op.f('ix_saved_properties_id'), table_name='saved_properties')
    op.drop_table('saved_properties')
    op.drop_index(op.f('ix_property_analyses_location_id'), table_name='property_analyses')
    op.drop_index(op.f('ix_property_analyses_id'), table_name='property_analyses')
    op.drop_table('property_analyses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_locations_lon'), table_name='locations')
    op.drop_index(op.f('ix_locations_lat'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
